### ISSUE TITLE
Physics bug

### ISSUE THREAD

**Issue by Dimandra2** [TrianglyRU/OrbinautFramework#12] opened 2024-03-14 20:05 UTC
If you make a full loop, the player may get stuck near it's bases(When the angle is approximately 37.97 or 322.03 degrees ). To replicate the glitch make a full loop and try to run in it without gaining too much speed. You will notice that character slows down on certain spots or even gets stuck.
![fix](https://github.com/TrianglyRU/OrbinautFramework/assets/93518504/64b09e58-f524-423c-aafb-dd407dbded94)

**Comment by TrianglyRU** [comment] 2024-03-15 05:41
This is not a bug but how pre-S3 slope physics work. Smooth rotation has different (wider) angle range compared to regular 45-degree rotation so that may have disoriented you. I'm closing the issue for now, but I'd like for you to attach a video so I can make sure there is no misunderstanding between us

P.S. Orbinaut Framework 1 is no longer supported and all gameplay-related glitches are bugs will not be fixed

**Closed by TrianglyRU** 2024-03-15 05:41 UTC

**Comment by Dimandra2** [comment] 2024-03-15 11:24
How do I download Orbinaut Framework 2? I thought that was the second version

**Comment by TrianglyRU** [comment] 2024-03-15 11:53
You may upload it however you want, a cloud storage will work as well. Orbinaut Framework 2 is in development and set to release SAGE this year, stay tuned!

**Comment by Dimandra2** [comment] 2024-03-15 12:04
I cant replicate the glitch in your new release. So no need to attach the video then. I guess it was I who messed up)

**Comment by Dimandra2** [comment] 2024-03-15 12:32
Although, maybe you have a thought to why this happens? Because I've been struggling with this bug for a long time. P.S I did modify the framework but haven't touched the physics. Here is the video: https://drive.google.com/file/d/1hRVXz4M89b10XeKyV8DY_64vfb4V6BRi/view?usp=drive_link
